[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; connect-src 'self' https://www.googleapis.com https://cdn.jsdelivr.net; img-src 'self' data: blob: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; media-src 'self' blob: data: https:; object-src 'none'; base-uri 'self'; frame-src 'self' https://jimmywarting.github.io; frame-ancestors 'none'; form-action 'self'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
